const Constants = {
    "DEFAULT_URL_TYPE": "DEFAULT",
    "ALL_COMBINATIONS": "*",
    "SPECIFIC_URL": "SPEC",
    "SCRAPE_QUANTITIES": "SCRAPE_QUANTITIES",
    "SCRAPE_QUANTITIE_COMPLETED": "SCRAPE_QUANTITIE_COMPLETED",
    "QUANTITY_TYPE": "QUANTITY",
    "SCRAPE_DOSAGES": "SCRAPE_DOSAGES",
    "RESET_DOSAGES": "RESET_DOSAGES",
    "RESET_FORMS": "RESET_FORMS",
    "SCRAPE_DOSAGES_COMPLETED": "SCRAPE_DOSAGES_COMPLETED",
    "DOSAGE_TYPE": "DOSAGE",
    "SCRAPE_FORMS": "SCRAPE_FORMS",
    "SCRAPE_FORMS_COMPLETED": "SCRAPE_FORMS_COMPLETED",
    "SCRAPE_FOR_ZIP_COMPLETED": "SCRAPE_FOR_ZIP_COMPLETED",
    "PRICE_REQUEST_TRIGGERED": "PRICE_REQUEST_TRIGGERED",
    "SCRAPE_FOR_ZIP_FAILED": "SCRAPE_FOR_ZIP_FAILED",
    "FORM_TYPE": "FORM",
    "BOT_MESSAGE_UP": "BOT_MESSAGE_UP",
    "BOT_MESSAGE_VERIFIED": "BOT_MESSAGE_VERIFIED",
    "BOT_MESSAGE_VERIFICATION_FAILURE": "BOT_MESSAGE_VERIFICATION_FAILURE",
    "PAGE_SCRAPE_DONE": "PAGE_SCRAPE_DONE",
    "WILD_CARD_OUTPUT": "WILD_CARD_OUTPUT",
    "ALL_REQUESTS_DONE": "ALL_REQUESTS_DONE",

    "SCRAPE_LABELS": "SCRAPE_LABELS",
    "ZIP_CODE_SET_SUCCESS": "ZIP_CODE_SET_SUCCESS",
    "ZIP_CODE_SET_ERROR": "ZIP_CODE_SET_ERROR",
    "SCRAPE_LABELS_COMPLETED": "SCRAPE_LABELS_COMPLETED",
    "LABEL_TYPE": "LABEL"
};

module.exports = Constants;